# Generated by Django 3.2.7 on 2021-09-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture_pad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='month',
            new_name='day',
        ),
    ]
