# Generated by Django 3.2.7 on 2021-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture_pad', '0002_rename_month_note_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='owner',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='month',
            name='name',
            field=models.CharField(default='name of month', max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='textContent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='name',
            field=models.IntegerField(default=2021),
        ),
    ]
