# Generated by Django 3.2.7 on 2021-09-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture_pad', '0003_auto_20210913_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='textContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
